<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Statistika</h2>
        <?php
        $date = 0;
        $counter = 0;
        ?>
        <script type="text/javascript">
            $(function ()
            {

            <?php foreach ($rows as $row): ?>
                <?php if ($date==0): ?>
                    <?php $date = $row["date"]; ?>

                        $("#chartContainer<?php echo $counter; ?>").dxChart({
                dataSource: [

                    <?php elseif ($date!=$row["date"]): ?>
                    <?php
                    $counter++;
                    ?>
                ],
                    series: {
                        argumentField: "hour",
                        valueField: "count",
                        name: "Tvīti pa stundām no <?php echo $date; ?>",
                        type: "splineArea",
                        color: '#ffa500'
                    }
                });
                        $("#chartContainer<?php echo $counter; ?>").dxChart({
                dataSource: [
                    <?php $date = $row["date"]; ?>
                    <?php endif; ?>

                {hour: <?php echo $row["hour"];?>, count: <?php echo $row["count"];?>},
                <?php endforeach; ?>
            ],
                series: {
                    argumentField: "hour",
                    valueField: "count",
                    name: "Tvīti pa stundām no <?php echo $date; ?>",
                    type: "splineArea",
                    color: '#ffa500'
                }
            });
            });
        </script>
        <div class="content">
            <select id="select_date" class="uk-form-large uk-form-width-medium">
                <?php foreach ($dates as $date):?>
                <option value="<?php echo $date["date"];?>"><?php echo $date["date"];?></option>
                <?php endforeach; ?>
            </select>
            <?php for ($i=0; $i<=$counter; $i++): ?>
            <div class="pane" id="chart<?php echo $i; ?>">
                <div class="long-title"><h3></h3></div>
                <div id="chartContainer<?php echo $i; ?>" style="width: 100%; height: 440px;"></div>
                <div class="credits"></div>
            </div>
            <?php endfor; ?>
        </div>
        <script type="text/javascript">
            $(function ()
            {
            <?php for ($i=1; $i<=$counter; $i++): ?>
                $('#chart<?php echo $i; ?>').hide();
                <?php endfor; ?>
                $('#select_date').change(function () {
                <?php foreach ($dates as $key => $date):?>
                    if ($('#select_date option:selected').text() == "<?php echo $date["date"];?>")
                    {
                        <?php for ($i=0; $i<=$counter; $i++): ?>
                        $('#chart<?php echo $i; ?>').hide();
                        <?php endfor; ?>
                        $('#chart<?php echo $key ?>').show();
                    }
                    <?php endforeach; ?>
                });
            });
        </script>
    </div>
</div>