<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1"><?php echo $isPost ? "Lietotāju skaits tvītu skaitam ".$from." - ".$to : "Lietotāju skaits pret tvītu skaitu" ?></h2>
        <script type="text/javascript">
            $(function ()
            {
                var dataSource = [
                <?php foreach ($counts as $count):?>
                    { tweets: <?php echo $count["tweets"]; ?>, users: <?php echo $count["users"] ?>},
                    <?php endforeach; ?>
                ];

                $("#chartContainer").dxChart({
                    dataSource: dataSource,
                    commonSeriesSettings: {
                        argumentField: "tweets"
                    },
                    series: [
                        { valueField: "users", name: "x - Tvīti, y - Lietotāji" }
                    ],
                    argumentAxis:{
                        grid:{
                            visible: true
                        }
                    },
                    tooltip:{
                        enabled: true
                    },
                    legend: {
                        verticalAlignment: "bottom",
                        horizontalAlignment: "center"
                    },
                    commonPaneSettings: {
                        border:{
                            visible: true,
                            right: false
                        }
                    }
                });
            });
        </script>
        <div class="content">
            <div class="">
                <form action="" method="post" onsubmit="return isValidForm()">
                    <p class="statistic">Izvēlies tvītu skaita ierobežojumu
                        <input type="text" name="from" id="from" required>
                        līdz
                        <input type="text" name="to" id="to" required>
                        <button type="submit" id="show">Parādīt</button>
                    </p>
                </form>

            </div>
            <div class="pane">
                <div class="long-title"><h3></h3></div>
                <div id="chartContainer" style="width: 100%; height: 440px;"></div>
                <div class="credits"></div>
            </div>
        </div>

        <script>
            var isValidForm = function(){
                var from = parseInt($('#from').val());
                var to = parseInt($('#to').val());
                if (from > to) return false;
                if (from < 0 || to < 0) return false;
                return true;
            };
        </script>
    </div>
</div>