<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Vispārējā informācija</h2>
        <p class="statistic">Letiņš Tvītiņš ir sistēma, kas, izmantojot <span class="highlight-orange">twitter streaming API</span>, veic <span class="highlight-orange">Latvijas</span> twitter verses analīzi un statistikas izveidi</p>

        <p class="statistic">Sistēma ir atradusi <span class="highlight-orange"><?php echo $this->formatNumber($existingUserCount) ?></span> latviešu <span class="highlight-orange">lietotājus</span></p>

        <p class="statistic">Pēdējā mēnesī sistēma ir savākusi <span class="highlight-brick"><?php echo $this->formatNumber($existingTweetCount) ?></span> unikālu <span class="highlight-red">tvītu</span></p>

        <p class="statistic">Visaktīvākā diena ir bijusi  <span class="highlight-brick"><?php echo $maxTweets['date'] ?></span> ar <span class="highlight-red"><?php echo $this->formatNumber($maxTweets['count']) ?></span> tvītiem</p>

        <p class="statistic">Ņem vērā, ka sistēma māk meklēt tikai <span class="highlight-brick">publiskus</span> lietotājus!</p>
    </div>
</div>

<div class="content-2">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Lietotāju aktivitāte no sistēmas sākuma</h2>
        <script type="text/javascript">
            $(function ()
                {
                    $("#chartContainer").dxChart({
                        dataSource: [
                            <?php foreach ($tweetCountByDay as $key => $day): ?>
                            {day: "<?php echo $day['date'] ?>", oranges: <?php echo $day['count'] ?>},
                            <?php endforeach; ?>

                        ],

                        series: {
                            argumentField: "day",
                            valueField: "oranges",
                            name: "Tvīti",
                            type: "bar",
                            color: '#6CAC26'
                        }
                    });
                }

            );
        </script>
        <div id="chartContainer" style="width: 100%; height: 440px;"></div>
    </div>
</div>

<div class="content-3">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Vēlviens jiber jaber</h2>
        <script type="text/javascript">
            $(function ()
                {
                    $("#chartContainer2").dxChart({
                        dataSource: [
                            <?php foreach ($tweetCountByDay as $key => $day): ?>
                            {day: "<?php echo $day['date'] ?>", oranges: <?php echo $day['count'] ?>},
                            <?php endforeach; ?>

                        ],

                        series: {
                            argumentField: "day",
                            valueField: "oranges",
                            name: "Tvīti",
                            type: "bar",
                            color: '#45ada8'
                        }
                    });
                }

            );
        </script>
        <div id="chartContainer2" style="width: 100%; height: 440px;"></div>
    </div>
</div>

<div class="content-4">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Un pat vēlviens jiber jaber</h2>
        <script type="text/javascript">
            $(function ()
                {
                    $("#chartContainer3").dxChart({
                        dataSource: [
                            <?php foreach ($tweetCountByDay as $key => $day): ?>
                            {day: "<?php echo $day['date'] ?>", oranges: <?php echo $day['count'] ?>},
                            <?php endforeach; ?>

                        ],

                        series: {
                            argumentField: "day",
                            valueField: "oranges",
                            name: "Tvīti",
                            type: "bar",
                            color: '#45ada8'
                        }
                    });
                }

            );
        </script>
        <div id="chartContainer3" style="width: 100%; height: 440px;"></div>
    </div>
</div>
