<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Statistika</h2>
        <ul>
            <li><a href="<?php echo BASE_URL ?>statistics/byhour">Statistika pa stundām</a></li>
            <li><a href="<?php echo BASE_URL ?>statistics/timeperiod">Statistika laika periodā</a></li>
            <li><a href="<?php echo BASE_URL ?>statistics/userstweets">Lietotāju un to tvītu skaita statistika</a></li>
        </ul>
    </div>
</div>
