<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Statistika</h2>
            <a href="<?php echo BASE_URL ?>statistics/timeperiod" class="uk-thumbnail">
                <img src="<?php echo IMG_PATH; ?>statistics_timeperiod.png" alt="">
                <div class="uk-thumbnail-caption">Statistika laika periodā</div>
            </a>
            <a href="<?php echo BASE_URL ?>statistics/userstweets" class="uk-thumbnail">
                <img src="<?php echo IMG_PATH;?>statistics_tweetcount.png" alt="">
                <div class="uk-thumbnail-caption">Lietotāju un to tvītu skaita statistika</div>
            </a>
            <a href="<?php echo BASE_URL ?>statistics/topwords" class="uk-thumbnail">
                <div class="uk-thumbnail-caption">Biežāk lietotie vārdi</div>
            </a>
            <a href="<?php echo BASE_URL ?>statistics/deviceinfo" class="uk-thumbnail">
                <div class="uk-thumbnail-caption">Izmantotās ierīces</div>
            </a>
    </div>
</div>
