<html>
    <head>
        <title><?php echo $GLOBALS['sitename'];?><?php if (isset($pageTitle)) echo ' | ' . $pageTitle; ?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link rel="stylesheet" type="text/css" href="<?php echo CSS_PATH ?>uikit.css">
        <link rel="stylesheet" type="text/css" href="<?php echo CSS_PATH ?>style.css">
        <script src="<?php echo JS_PATH ?>charts/jquery-1.9.1.min.js"></script>
        <script src="<?php echo JS_PATH ?>charts/knockout-2.2.1.js"></script>
        <script src="<?php echo JS_PATH ?>charts/globalize.min.js"></script>
        <script src="<?php echo JS_PATH ?>charts/dx.chartjs.js"></script>
        <script src="<?php echo JS_PATH ?>uikit.min.js"></script>
        <script src="<?php echo JS_PATH ?>functions.js"></script>
        <script src="<?php echo JS_PATH ?>markerclusterer.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
        <script src="<?php echo BASE_URL ?>timechart/timechart.js"></script>
    </head>
    <body>
        <div class="wrapper">

            <!-- HEADER -->
            <nav class="uk-navbar uk-navbar-attached">
                <div class="uk-container uk-container-center">
                    <a href="<?php echo BASE_URL ?>" class="uk-navbar-brand uk-float-left">Letiņš Tvītiņš</a>
                    <ul class="main-nav uk-float-right">
                        <li><a href="<?php echo BASE_URL ?>" class="nav-item">Sākums</a></li>
                        <li><a href="<?php echo BASE_URL ?>coordinates" class="nav-item">Vietas</a></li>
                        <li><a href="<?php echo BASE_URL ?>tops" class="nav-item">Topi</a></li>
                        <li><a href="<?php echo BASE_URL ?>statistics" class="nav-item">Statistika</a></li>
                    </ul>
                </div>
            </nav>

            <!-- CONTENT -->
            <?php echo $content ?>

            <!-- FOOTER -->
            <div class="uk-container uk-container-center footer">
            </div>

        </div>
    </body>
</html>