<div class="uk-grid">
    <div class="uk-width-1-2">
        <table class="uk-table uk-table-hover">
            <?php $counter = 1; $counter2 = 1; ?>
            <caption>Top 20 lietotāji, kas pieminēti visvairāk</caption>
            <thead>
            <tr>
                <th>Vieta</th>
                <th>Lietotājs</th>
                <th>Skaits</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $user): ?>
            <tr>
                <td class="uk-width-1-10"><?php echo $counter; $counter++; ?>.</td>
                <td class="uk-width-4-10"><?php echo $user["screen_name"] ?></td>
                <td class="uk-width-5-10"><?php echo $user["count"] ?></td>
            </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="uk-width-1-2">
        <table class="uk-table uk-width-1-2 uk-table-hover">
            <caption>Top 20 hashtagi, kas izmantoti visvairāk</caption>
            <thead>
            <tr>
                <th>Vieta</th>
                <th>Hashtag</th>
                <th>Skaits</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($hashtags as $hashtag): ?>
            <tr>
                <td class="uk-width-1-10"><?php echo $counter2; $counter2++; ?>.</td>
                <td class="uk-width-4-10"><?php echo $hashtag["hashtag"] ?></td>
                <td class="uk-width-5-10"><?php echo $hashtag["count"] ?></td>
            </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>