<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Vispārējā informācija</h2>
        <p class="statistic">Letiņš Tvītiņš ir sistēma, kas veic <span class="highlight-badge">Latvijas</span> <span class="highlight-badge">twitter</span> verses analīzi un <span class="highlight-badge">statistiku</span></p>

        <p class="statistic">Sistēma ir atradusi <span class="highlight-badge"><?php echo $this->formatNumber($existingUserCount) ?></span> latviešu <span class="highlight-badge">lietotājus</span></p>

        <p class="statistic">Pēdējā mēnesī sistēma ir savākusi <span class="highlight-badge"><?php echo $this->formatNumber($lastMonthTweetCount) ?></span> unikālu <span class="highlight-badge">tvītu</span></p>

        <p class="statistic">Kopā savākti <span class="highlight-badge"><?php echo $this->formatNumber($existingTweetCount) ?></span> unikālu tvītu</p>

        <p class="statistic">Visaktīvākā diena ir bijusi  <span class="highlight-badge"><?php echo $maxTweets['date'] ?></span> ar <span class="highlight-badge"><?php echo $this->formatNumber($maxTweets['count']) ?></span> tvītiem</p>

        <p class="statistic">Ņem vērā, ka sistēma māk meklēt tikai <span class="highlight-badge">publiskus</span> lietotājus!</p>
    </div>
</div>

<div class="content-2">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Lietotāju aktivitāte no sistēmas sākuma</h2>
        <script type="text/javascript">
            $(function() {
                $("#chartContainer").dxChart({
                    dataSource: [
                        <?php foreach ($tweetCountByDay as $key => $day): ?>
                        {day: "<?php echo $day['date'] ?>", oranges: <?php echo $day['count'] ?>},
                        <?php endforeach; ?>

                    ],
                    series: {
                        argumentField: "day",
                        valueField: "oranges",
                        name: "Tvīti",
                        type: "bar",
                        color: '#6CAC26'
                    }
                });
            });
        </script>
        <div id="chartContainer" style="width: 100%; height: 440px;"></div>
    </div>
</div>
