<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Vispārējā informācija</h2>
        <p class="statistic">Letiņš Tvītiņš ir sistēma, kas veic <span class="highlight-badge">Latvijas</span> <span class="highlight-badge">twitter</span> verses analīzi un <span class="highlight-badge">statistiku</span></p>

        <p class="statistic">Sistēma ir atradusi <span class="highlight-badge"><?php echo $this->formatNumber($existingUserCount) ?></span> latviešu <span class="highlight-badge">lietotājus</span></p>

        <p class="statistic">Pēdējā mēnesī sistēma ir savākusi <span class="highlight-badge"><?php echo $this->formatNumber($lastMonthTweetCount) ?></span> unikālu <span class="highlight-badge">tvītu</span></p>

        <p class="statistic">Kopā savākti <span class="highlight-badge"><?php echo $this->formatNumber($existingTweetCount) ?></span> unikālu tvītu</p>

        <p class="statistic">Visaktīvākā diena ir bijusi  <span class="highlight-badge"><?php echo $maxTweets['date'] ?></span> ar <span class="highlight-badge"><?php echo $this->formatNumber($maxTweets['count']) ?></span> tvītiem</p>

        <p class="statistic">Ņem vērā, ka sistēma māk meklēt tikai <span class="highlight-badge">publiskus</span> lietotājus!</p>
    </div>
</div>

<div class="content-2">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Pēdējo nedēļu aktivitāte</h2>
        <script type="text/javascript">
            $(function() {
                $("#chartContainerWeek").dxChart({
                    dataSource: [
                        <?php foreach ($tweetCountByTwoWeeks as $key => $day): ?>
                        { day: "<?php echo date('D', strtotime($day['date'])) ?>",
                          count: <?php echo $day['count_new'] ?>,
                          count_previous: <?php isset($day[0]) ? $count = $day[0] : $count = 0; echo $count; ?> },
                        <?php endforeach; ?>

                    ],
                    commonSeriesSettings: {
                        type: 'spline',
                        argumentField: 'day',
                        width: 5,
                        hoverStyle: {
                            width: 7
                        }
                    },
                    commonAxisSettings: {
                        grid: {
                            visible: true
                        }
                    },
                    series: [
                        { valueField: 'count', name: 'Šī nedēļā', color: '#0779A6' },
                        { valueField: 'count_previous', name: 'Iepriekšējā nedēļa', color: '#3BA9D3' }
                    ],
                    tooltip:{
                        enabled: true
                    },
                    legend: {
                        verticalAlignment: 'bottom',
                        horizontalAlignment: 'center'
                    },
                    commonPaneSettings: {
                        border:{
                            visible: true,
                            bottom: false
                        }
                    }
                });
            });
        </script>
        <div id="chartContainerWeek" style="width: 100%; height: 440px;"></div>
    </div>
</div>

<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1">Lietotāju aktivitāte no sistēmas sākuma</h2>
        <script type="text/javascript">
            $(function() {
                $("#chartContainer").dxChart({
                    dataSource: [
                        <?php foreach ($tweetCountByDay as $key => $day): ?>
                        {day: "<?php echo $day['date'] ?>", oranges: <?php echo $day['count'] ?>},
                        <?php endforeach; ?>

                    ],
                    series: {
                        argumentField: "day",
                        valueField: "oranges",
                        name: "Tvīti",
                        type: "bar",
                        color: '#0779A6'
                    }
                });
            });
        </script>
        <div id="chartContainer" style="width: 100%; height: 440px;"></div>
    </div>
</div>
