<div class="content-1 top-wrapper" data-base-url="<?php echo BASE_URL ?>">
    <div class="uk-container uk-container-center">
        <div class="uk-grid">
            <div class="uk-width-1-2">
                <div class="uk-panel uk-panel-box data-table" data-next-url="tops/mentions">
                    <h2 class="uk-h1 title">Lietotāji, kas pieminēti visvairāk</h2>
                </div>
            </div>
            <div class="uk-width-1-2">
                <div class="uk-panel uk-panel-box data-table" data-next-url="tops/hashtags">
                    <h2 class="uk-h1 title">Hashtagi, kas izmantoti visvairāk</h2>
                </div>
            </div>
        </div>
        <div class="uk-grid">
            <div class="uk-width-1-2">
                <div class="uk-panel uk-panel-box data-table" data-next-url="tops/retweets">
                    <h2 class="uk-h1 title">Populārākie retvīti</h2>
                </div>  
            </div>
            <div class="uk-width-1-2">
                <div class="uk-panel uk-panel-box data-table" data-next-url="tops/sources">
                    <h2 class="uk-h1 title">Tvītošanas veidi</h2>
                </div>
            </div>
        </div>
    </div>
</div>