<div class="content-1 top-wrapper" data-base-url="<?php echo BASE_URL ?>" data-img-path="<?php echo IMG_PATH ?>">
    <div class="uk-container uk-container-center">
        <div class="uk-grid">
            <div class="uk-width-1-2">
                <div class="uk-panel uk-panel-box data-table mentions">
                    <h2 class="uk-h1 title">Lietotāji, kas pieminēti visvairāk</h2>
                    <div class="buttons" data-model="mentions">
                        <span>Kārtot pēc</span>
                        <button data-period="day" class="btn">Dienas</button>
                        <button data-period="week" class="btn">Nedēļas</button>
                        <button data-period="month" class="btn">Mēneša</button>
                        <button data-period="total" class="btn">Kopējā</button>
                    </div>
                </div>
            </div>
            <div class="uk-width-1-2">
                <div class="uk-panel uk-panel-box data-table hashtags">
                    <h2 class="uk-h1 title">Hashtagi, kas izmantoti visvairāk</h2>
                    <div class="buttons" data-model="hashtags">
                        <span>Kārtot pēc</span>
                        <button data-period="total" class="btn">Kopējā</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="uk-grid">
            <div class="uk-width-1-2">
                <div class="uk-panel uk-panel-box data-table retweets">
                    <h2 class="uk-h1 title">Populārākie retvīti</h2>
                    <div class="buttons" data-model="retweets">
                        <span>Kārtot pēc</span>
                        <button data-period="day" class="btn">Dienaa</button>
                        <button data-period="week" class="btn">Nedēļas</button>
                        <button data-period="month" class="btn">Mēneā</button>
                        <button data-period="total" class="btn">Kopējā</button>
                    </div>
                </div>  
            </div>
            <div class="uk-width-1-2">
                <div class="uk-panel uk-panel-box data-table sources">
                    <h2 class="uk-h1 title">Tvītošanas veidi</h2>
                    <div class="buttons" data-model="sources">
                        <span>Kārtot pēc</span>
                        <button data-period="day" class="btn">Dienas</button>
                        <button data-period="week" class="btn">Nedēļas</button>
                        <button data-period="month" class="btn">Mēneša</button>
                        <button data-period="total" class="btn">Kopējā</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>