<?php $currentLink =  "http://$_SERVER[HTTP_HOST]$_SERVER[REDIRECT_URL]" . "?pointid=" . $venueId . "&name=" . urlencode($pageTitle) ?>
<div class="content-1">
    <div class="uk-container uk-container-center">
        <h2 class="uk-h1"><?php echo $pageTitle ?></h2>
        <div class="uk-grid venue-info">
            <div class="uk-width-3-10 uk-panel uk-panel-box">
                <table class="uk-table users">
                    <thead>
                        <tr>
                            <th>Tvītu skaits</th>
                            <th>Lietotājs</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $count = 0; foreach ($users as $user): ?>
                            <tr class="<?php echo $user['user_id'] ?>">
                                <td class="count"><?php echo $user['count'] ?></td>
                                <?php $screenName = $user['screen_name'] ?>
                                <td>
                                    <a href="https://twitter.com/<?php echo $screenName ?>">
                                        <img src="<?php echo $user['image_url'] ?>"/>
                                        <span><?php echo $screenName ?></span>
                                    </a>
                                </td>
                            </tr>
                            <?php $count++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <button class="uk-button" type="button" onclick="loadVenueData(this, 'usersfrom', 'users')" 
                        data-count="<?php echo $count ?>"
                        data-load-link="<?php echo $currentLink ?>"
                        data-max-count="<?php echo $usersCount ?>">Ielādēt vēl</button>
                <button class="uk-button to-top" onclick="scrollToTop()">Uz augšu</button>
            </div>
            <div class="uk-width-6-10 uk-push-1-10 uk-panel uk-panel-box">
                <table class="uk-table tweets">
                    <thead>
                        <tr>
                            <th>Laiks/autors</th>
                            <th>Tvīts</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $count = 0; foreach ($tweets as $tweet): ?>
                            <tr class="<?php echo $tweet['user'] ?>">
                                <td>
                                    <span><?php echo $tweet['created_at'] ?></span>
                                    <span><a href="https://twitter.com/<?php echo $tweet['screen_name'] ?>">
                                        <?php echo $tweet['screen_name'] ?></a>
                                    </span>
                                </td>
                                <td><?php echo $tweet['text'] ?></td>
                            </tr>
                            <?php $count++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <button class="uk-button" type="button" onclick="loadVenueData(this, 'tweetsfrom', 'tweets')" 
                        data-count="<?php echo $count ?>"
                        data-load-link="<?php echo $currentLink ?>"
                        data-max-count="<?php echo $tweetsCount ?>">Ielādēt vēl</button>
                <button class="uk-button to-top" onclick="scrollToTop()">Uz augšu</button>
            </div>
        </div>
    </div>
</div>